@{
    Culture = 'fr-FR'
    Direction = 'LeftToRight'
    Strings = @{
        'app.tagline' = 'Desactivation / suppression de Microsoft Defender (pare-feu preserve)'
        'menu.disable' = '  [1] Disable  (reversible ; strategies + taches + mode passif + services)'
        'menu.remove' = '  [2] Remove   (agressif ; Mode sans echec recommande ; SecHealthUI + SafeBoot)'
        'menu.restore' = '  [3] Restore  (rejouer et verifier la base enregistree)'
        'menu.status' = '  [4] Status   (afficher l etat actuel de Defender + du pare-feu)'
        'menu.health' = '  [5] Health   (comparer l etat actuel a la cible attendue)'
        'menu.offline' = '  [6] Prepare Offline (generer le bundle de suppression WinRE/hors ligne)'
        'menu.quit' = '  [Q] Quitter'
        'menu.select' = 'Selection'
        'menu.invalid' = "  Selection incorrecte : {0}"
        'cli.aborted' = 'Abandonne.'
        'cli.health.target' = 'Cible Health : {0}'
        'cli.health.summary' = 'OK={0} Derive={1} Inconnu={2} Total={3}'
        'cli.health.reapply' = 'Plan de reapplication :'
        'cli.health.reapply.item' = ' - {0}'
        'cli.operation.verified' = 'Operation verifiee : tentees={0} modifiees={1} verifiees={2}'
        'cli.reboot.prompt' = 'Redemarrer maintenant ? (Y/n)'
        'cli.error.title' = 'Erreur DisableDefender'
        'gui.recovery.hub' = 'Centre de recuperation'
        'gui.recovery.title' = 'Verifiez la cible selectionnee avant de reprendre, restaurer ou exporter les preuves.'
        'gui.recovery.subtitle' = 'Toutes les requetes et exportations restent locales. Une annulation s arrete a une limite sure.'
        'gui.recovery.refresh' = 'Actualiser les preuves'
        'gui.recovery.cancel' = 'Annuler la requete'
        'gui.recovery.done' = 'Termine'
        'gui.recovery.live' = 'PREUVES DE LA CIBLE EN DIRECT'
        'gui.recovery.drift' = 'Derive exacte (12 premieres)'
        'gui.recovery.phase' = 'RECUPERATION DE PHASE'
        'gui.recovery.snapshots' = 'INSTANTANES ET DIFF'
        'gui.recovery.snapshots.description' = 'Choisissez une base, enregistrez un instantane cible ou comparez l etat direct.'
        'gui.recovery.exports' = 'EXPORTATIONS LOCALES'
        'gui.recovery.exports.description' = 'Les exportations utilisent la cible selectionnee et ne televersent rien.'
        'gui.recovery.sense' = 'Sense est exclu sauf si la commande selectionnee l inclut explicitement.'
        'gui.recovery.snapshot' = 'Enregistrer un instantane'
        'gui.recovery.compare' = 'Comparer au direct'
        'gui.recovery.report' = 'Rapport HTML'
        'gui.recovery.support' = 'Bundle de support'
        'gui.recovery.target' = 'Cible Health'
        'gui.security.open' = 'Ouvrir la securite Windows'
        'gui.log.copy' = 'Copier'
        'gui.log.export' = 'Exporter'
        'gui.log.clear' = 'Effacer'
        'gui.operation.cancel' = 'Annuler l operation'
        'gui.action.disable' = 'Disable Defender'
        'gui.action.remove' = 'Full Remove'
        'gui.action.restore' = 'Restore Defender'
        'gui.action.repair' = 'Reparer les valeurs par defaut'
        'gui.action.refresh' = 'Actualiser le statut'
    }
}
